### ISSUE TITLE
Windowsで数式が文字化けします

### ISSUE THREAD

**Issue by dfukagaw28** [koki0702/dezero-p100#1]
### 概要

Windows 環境で「強化学習100題」を開くと一部の数式が文字化けします。

![image](https://github.com/koki0702/dezero-p100/assets/8717739/7334fda9-0739-48bb-814f-e7642e72dfb2)

Apple 環境（試したのは iPadOS 16.4.1 + Brave 1.50）では同じ現象を確認できません。

### 再現手順

- Web ブラウザで次の URL を開く
  - https://koki0702.github.io/dezero-p100/chapter3/

### 期待した動作

- $\Gamma_\tau$ (Gamma tau) でなく $G_t$ (G t) が表示される
- $\sigma$ でなく $s$ が表示される
- ・・・など

### 使用環境

- OS: Windows 11 Pro (22H2)
- ブラウザ: Google Chrome Version 113.0.5672.92 (Official Build) (64-bit)

### 追加情報

わかりやすい書籍や確認問題を作成・提供していただきありがとうございます。
ゼミの勉強会で利用させていただいております。
お時間のある時に修正をお願いできますとたいへん助かります。

おそらく font-family の問題で，現状は `CMSY10,CMEX10,Symbol,Times New Roman,Times,serif` となっており Windows 環境では `Symbol` が採用されているようです。`Symbol` を削除する（あるいは優先順位を下げる）と文字化けが解消されます。

どうぞよろしくお願い申し上げます。

**Comment by koki0702** [comment]
ご報告ありがとうございます。

とりあえず`Symbol` を削除しました。

手元にWindows環境がなく、もし可能でしたらご確認いただけると助かります。

**Comment by dfukagaw28** [comment]
ありがとうございます！
問題なく表示されるようになりました！
